### ISSUE TITLE
clicking enter in search bar not user friendly

### ISSUE THREAD

**Issue by leenkededonder** [oSoc20/urban-brussels#67]
when searching and clicking enter when there are still multiple suggestions, the user doesn't understand why it doesn't go to Horta

**Comment by jbelien** [comment]
I don't get this issue, you don't need to use <kbd>ENTER</kbd>.

1. Start typing ;
2. List appears ;
3. Click on list item ;
4. Redirects to buildings list (on landing page) OR add filter and refreshes list (on buildings list)

**Comment by katevda** [comment]
Here the issue was more that you have a list containing only an architect and a street, that the architect option is coloured/highlighted, so it might seem to users that when pressing enter you would immediately search for the architect, instead of still having to choose between the architect and a street. (This is more clear when the choice is between an architect and a style for example, as they're both highlighted)

(image below the image Leenke provided in Discord)
![image](https://user-images.githubusercontent.com/4929939/88800024-be429680-d1a7-11ea-91b3-c0e6d31c30f0.png)

**Comment by jbelien** [comment]
Closed by 9a5c8d2123394fbea22d0c0e7708228347915236
